In [21]:
#eğer benim hedef değişkenim kategorik bir veriyse bu classification problemidir 
# Yani logistic regression kullanılabilir !!!
# Logistic regression ile sayısal değerler üzerinden sınıflandırma yapabiliriz !!! 
#bunu yaparken logistic fonksiyon çiziyor !!!
#1. kütüphaneler 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [22]:
veriler = pd.read_csv("veriler.csv")
veriler.head()

ulke  boy  kilo  yas cinsiyet
0   tr  130    30   10        e
1   tr  125    36   11        e
2   tr  135    34   10        k
3   tr  133    30    9        k
4   tr  129    38   12        e

In [23]:
x = veriler.iloc[:,1:4]
y=veriler.iloc[:,-1:]

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=0)

In [25]:
x_train.head()

boy  kilo  yas
8   177    60   22
6   190    80   25
16  193    90   23
4   129    38   12
2   135    34   10

In [26]:
y_train.head()

cinsiyet
8         k
6         e
16        e
4         e
2         k

In [27]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(x_train)
X_test=sc.transform(x_test)

In [28]:
X_train

array([[ 0.45049444, -0.29657884, -0.26680787],
       [ 1.00824945,  0.5096549 ,  0.        ],
       [ 1.13696215,  0.91277178, -0.17787191],
       [-1.6089087 , -1.18343596, -1.15616745],
       [-1.35148331, -1.34468271, -1.33403936],
       [ 0.57920713,  0.91277178,  0.44467979],
       [ 0.87953676,  0.5096549 ,  0.17787191],
       [ 0.79372829,  1.51744708,  0.71148766],
       [ 0.36468597,  0.91277178,  0.88935957],
       [ 0.70791983,  0.8321484 ,  0.26680787],
       [-1.43729177, -1.50592946, -1.42297532],
       [-1.56600447, -1.50592946, -1.33403936],
       [ 0.32178174,  0.10653803,  1.95659106],
       [-0.27887751, -0.37720222,  1.2451034 ]])

In [29]:
X_test

array([[-0.10726058, -0.05470872,  0.6225517 ],
       [-0.06435635, -0.49813728,  0.17787191],
       [ 0.02145212, -0.21595547,  2.66807872],
       [-0.19306904, -0.33689053,  1.42297532],
       [-1.78052563, -1.26405934, -1.2451034 ],
       [-0.02145212, -0.45782559,  1.51191128],
       [-0.49339867, -0.69969571,  1.68978319],
       [-0.32178174, -1.10281259,  0.35574383]])

In [30]:
y_train

cinsiyet
8         k
6         e
16        e
4         e
2         k
5         e
17        e
9         e
7         e
18        e
3         k
0         e
15        e
12        k

In [33]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(random_state=0) 

In [34]:
log_reg.fit(X_train,y_train)

C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(random_state=0)

In [35]:
y_pred=log_reg.predict(X_test)

In [36]:
y_pred

array(['e', 'e', 'e', 'e', 'k', 'e', 'e', 'e'], dtype=object)

In [37]:
y_test

cinsiyet
20        k
10        k
14        k
13        k
1         e
21        k
11        k
19        k

In [38]:
from sklearn.metrics import confusion_matrix

In [41]:
cm = confusion_matrix(y_test,y_pred)

In [42]:
cm

array([[0, 1],
       [7, 0]], dtype=int64)